' PROGRAM NAME - OREGON        VERSION:01/01/78
' ORIGINAL PROGRAMMING BY BILL HEINEMANN - 1971
' SUPPORT RESEARCH AND MATERIALS BY DON RAVITSCH
' MINNESOTA EDUCATIONAL COMPUTING CONSORTIUM STAFF
' CDC CYBER 70/73-26      BASIC 3.1
' DOCUMENTATION BOOKLET 'OREGON' AVAILABLE FROM
'    MECC SUPPORT SERVICES
'    2520 BROADWAY DRIVE
'    ST. PAUL, MN  55113
'
' CONVERTED TO FREEBASIC - 2025
'
' *FOR THE MEANING OF THE VARIABLES USED, SEE END OF FILE*

' Variable declarations
DIM C$
DIM S$(1 TO 5)
DIM AS DOUBLE A, B, B1, B3, C, C1, D, D1, D3, D9
DIM AS DOUBLE E, F, F1, F2, F9, K8, L1, M, M1, M2, M9
DIM AS DOUBLE P, R1, S4, S5, S6, T, T1, X, X1

' Initialize random number generator
RANDOMIZE TIMER

PRINT "DO YOU NEED INSTRUCTIONS  (YES/NO)"
INPUT C$
IF C$ = "NO" THEN GOTO StartGame

PRINT
PRINT
' ***INSTRUCTIONS***
PRINT "THIS PROGRAM SIMULATES A TRIP OVER THE OREGON TRAIL FROM"
PRINT "INDEPENDENCE, MISSOURI TO OREGON CITY, OREGON IN 1847."
PRINT "YOUR FAMILY OF FIVE WILL COVER THE 2040 MILE OREGON TRAIL"
PRINT "IN 5-6 MONTHS --- IF YOU MAKE IT ALIVE."
PRINT
PRINT "YOU HAD SAVED $900 TO SPEND FOR THE TRIP, AND YOU'VE JUST"
PRINT "   PAID $200 FOR A WAGON."
PRINT "YOU WILL NEED TO SPEND THE REST OF YOUR MONEY ON THE"
PRINT "   FOLLOWING ITEMS:"
PRINT
PRINT "     OXEN - YOU CAN SPEND $200-$300 ON YOUR TEAM"
PRINT "            THE MORE YOU SPEND, THE FASTER YOU'LL GO"
PRINT "            BECAUSE YOU'LL HAVE BETTER ANIMALS"
PRINT
PRINT "     FOOD - THE MORE YOU HAVE, THE LESS CHANCE THERE"
PRINT "            IS OF GETTING SICK"
PRINT
PRINT "AMMUNITION - $1 BUYS A BELT OF 50 BULLETS"
PRINT "            YOU WILL NEED BULLETS FOR ATTACKS BY ANIMALS"
PRINT "            AND BANDITS, AND FOR HUNTING FOOD"
PRINT
PRINT "CLOTHING - THIS IS ESPECIALLY IMPORTANT FOR THE COLD"
PRINT "            WEATHER YOU WILL ENCOUNTER WHEN CROSSING"
PRINT "            THE MOUNTAINS"
PRINT
PRINT "MISCELLANEOUS SUPPLIES - THIS INCLUDES MEDICINE AND"
PRINT "            OTHER THINGS YOU WILL NEED FOR SICKNESS"
PRINT "            AND EMERGENCY REPAIRS"
PRINT
PRINT
PRINT "YOU CAN SPEND ALL YOUR MONEY BEFORE YOU START YOUR TRIP -"
PRINT "OR YOU CAN SAVE SOME OF YOUR CASH TO SPEND AT FORTS ALONG"
PRINT "THE WAY WHEN YOU RUN LOW. HOWEVER, ITEMS COST MORE AT"
PRINT "THE FORTS. YOU CAN ALSO GO HUNTING ALONG THE WAY TO GET"
PRINT "MORE FOOD."
PRINT "WHENEVER YOU HAVE TO USE YOUR TRUSTY RIFLE ALONG THE WAY,"
PRINT "YOU WILL BE TOLD TO TYPE IN A WORD (ONE THAT SOUNDS LIKE A"
PRINT "GUN SHOT). THE FASTER YOU TYPE IN THAT WORD AND HIT THE"
PRINT """RETURN"" KEY, THE BETTER LUCK YOU'LL HAVE WITH YOUR GUN."
PRINT
PRINT "AT EACH TURN, ALL ITEMS ARE SHOWN IN DOLLAR AMOUNTS"
PRINT "EXCEPT BULLETS"
PRINT "WHEN ASKED TO ENTER MONEY AMOUNTS, DON'T USE A ""$""."
PRINT
PRINT "GOOD LUCK!!!"

StartGame:
PRINT
PRINT
PRINT "HOW GOOD A SHOT ARE YOU WITH YOUR RIFLE?"
PRINT "  (1) ACE MARKSMAN,  (2) GOOD SHOT,  (3) FAIR TO MIDDLIN'"
PRINT "         (4) NEED MORE PRACTICE,  (5) SHAKY KNEES"
PRINT "ENTER ONE OF THE ABOVE -- THE BETTER YOU CLAIM YOU ARE, THE"
PRINT "FASTER YOU'LL HAVE TO BE WITH YOUR GUN TO BE SUCCESSFUL."
INPUT D9
IF D9 > 5 THEN D9 = 0

' ***INITIAL PURCHASES***
X1 = -1
K8 = 0
S4 = 0
F1 = 0
F2 = 0
M = 0
M9 = 0
D3 = 0

BuyOxen:
PRINT
PRINT
PRINT "HOW MUCH DO YOU WANT TO SPEND ON YOUR OXEN TEAM";
INPUT A
IF A < 200 THEN
    PRINT "NOT ENOUGH"
    GOTO BuyOxen
END IF
IF A > 300 THEN
    PRINT "TOO MUCH"
    GOTO BuyOxen
END IF

BuyFood:
PRINT "HOW MUCH DO YOU WANT TO SPEND ON FOOD";
INPUT F
IF F < 0 THEN
    PRINT "IMPOSSIBLE"
    GOTO BuyFood
END IF

BuyAmmo:
PRINT "HOW MUCH DO YOU WANT TO SPEND ON AMMUNITION";
INPUT B
IF B < 0 THEN
    PRINT "IMPOSSIBLE"
    GOTO BuyAmmo
END IF

BuyClothing:
PRINT "HOW MUCH DO YOU WANT TO SPEND ON CLOTHING";
INPUT C
IF C < 0 THEN
    PRINT "IMPOSSIBLE"
    GOTO BuyClothing
END IF

BuyMisc:
PRINT "HOW MUCH DO YOU WANT TO SPEND ON MISCELLANEOUS SUPPLIES";
INPUT M1
IF M1 < 0 THEN
    PRINT "IMPOSSIBLE"
    GOTO BuyMisc
END IF

T = 700 - A - F - B - C - M1
IF T < 0 THEN
    PRINT "YOU OVERSPENT--YOU ONLY HAD $700 TO SPEND.  BUY AGAIN"
    GOTO BuyOxen
END IF
B = 50 * B
PRINT "AFTER ALL YOUR PURCHASES, YOU NOW HAVE "; T; " DOLLARS LEFT"
PRINT
PRINT "MONDAY MARCH 29 1847"
PRINT
GOTO BeginTurn

' ***SETTING DATE***
SetDate:
IF M >= 2040 THEN GOTO FinalTurn
D3 = D3 + 1
PRINT
PRINT "MONDAY ";
SELECT CASE D3
    CASE 1: PRINT "APRIL 12 ";
    CASE 2: PRINT "APRIL 26 ";
    CASE 3: PRINT "MAY 10 ";
    CASE 4: PRINT "MAY 24 ";
    CASE 5: PRINT "JUNE 7 ";
    CASE 6: PRINT "JUNE 21 ";
    CASE 7: PRINT "JULY 5 ";
    CASE 8: PRINT "JULY 19 ";
    CASE 9: PRINT "AUGUST 2 ";
    CASE 10: PRINT "AUGUST 16 ";
    CASE 11: PRINT "AUGUST 31 ";
    CASE 12: PRINT "SEPTEMBER 13 ";
    CASE 13: PRINT "SEPTEMBER 27 ";
    CASE 14: PRINT "OCTOBER 11 ";
    CASE 15: PRINT "OCTOBER 25 ";
    CASE 16: PRINT "NOVEMBER 8 ";
    CASE 17: PRINT "NOVEMBER 22 ";
    CASE 18: PRINT "DECEMBER 6 ";
    CASE 19: PRINT "DECEMBER 20 ";
    CASE ELSE
        PRINT "YOU HAVE BEEN ON THE TRAIL TOO LONG  ------"
        PRINT "YOUR FAMILY DIES IN THE FIRST BLIZZARD OF WINTER"
        GOTO GameOver
END SELECT
PRINT "1847"
PRINT

' ***BEGINNING EACH TURN***
BeginTurn:
IF F < 0 THEN F = 0
IF B < 0 THEN B = 0
IF C < 0 THEN C = 0
IF M1 < 0 THEN M1 = 0
IF F < 13 THEN PRINT "YOU'D BETTER DO SOME HUNTING OR BUY FOOD AND SOON!!!!"
F = INT(F)
B = INT(B)
C = INT(C)
M1 = INT(M1)
T = INT(T)
M = INT(M)
M2 = M
IF S4 = 1 OR K8 = 1 THEN
    T = T - 20
    IF T < 0 THEN GOTO CantAffordDoctor
    PRINT "DOCTOR'S BILL IS $20"
    K8 = 0
    S4 = 0
END IF
IF M9 = 1 THEN
    PRINT "TOTAL MILEAGE IS 950"
    M9 = 0
ELSE
    PRINT "TOTAL MILEAGE IS "; M
END IF
PRINT "FOOD", "BULLETS", "CLOTHING", "MISC. SUPP.", "CASH"
PRINT F, B, C, M1, T

IF X1 = -1 THEN GOTO NoFortOption
X1 = X1 * (-1)

FortOption:
PRINT "DO YOU WANT TO (1) STOP AT THE NEXT FORT, (2) HUNT, ";
PRINT "OR (3) CONTINUE"
INPUT X
IF X < 1 OR X > 2 THEN X = 3
X = INT(X)
GOTO DoAction

NoFortOption:
PRINT "DO YOU WANT TO (1) HUNT, OR (2) CONTINUE"
INPUT X
IF X <> 1 THEN X = 2
X = X + 1
IF X = 3 THEN GOTO SkipHuntCheck
IF B <= 39 THEN
    PRINT "TOUGH---YOU NEED MORE BULLETS TO GO HUNTING"
    GOTO NoFortOption
END IF
SkipHuntCheck:
X1 = X1 * (-1)

DoAction:
SELECT CASE X
    CASE 1: GOTO StopAtFort
    CASE 2: GOTO GoHunting
    CASE ELSE: GOTO ContinueTravel
END SELECT

' ***STOPPING AT FORT***
StopAtFort:
PRINT "ENTER WHAT YOU WISH TO SPEND ON THE FOLLOWING"
PRINT "FOOD";
GOSUB GetPurchase
F = F + 2/3 * P
PRINT "AMMUNITION";
GOSUB GetPurchase
B = INT(B + 2/3 * P * 50)
PRINT "CLOTHING";
GOSUB GetPurchase
C = C + 2/3 * P
PRINT "MISCELLANEOUS SUPPLIES";
GOSUB GetPurchase
M1 = M1 + 2/3 * P
M = M - 45
GOTO ContinueTravel

' ***HUNTING***
GoHunting:
IF B <= 39 THEN
    PRINT "TOUGH---YOU NEED MORE BULLETS TO GO HUNTING"
    GOTO FortOption
END IF
M = M - 45
GOSUB ShootingRoutine
IF B1 <= 1 THEN
    PRINT "RIGHT BETWEEN THE EYES---YOU GOT A BIG ONE!!!!"
    PRINT "FULL BELLIES TONIGHT!"
    F = F + 52 + RND * 6
    B = B - 10 - RND * 4
ELSEIF 100 * RND < 13 * B1 THEN
    PRINT "YOU MISSED---AND YOUR DINNER GOT AWAY....."
ELSE
    F = F + 48 - 2 * B1
    PRINT "NICE SHOT--RIGHT ON TARGET--GOOD EATIN' TONIGHT!!"
    B = B - 10 - 3 * B1
END IF

ContinueTravel:
IF F < 13 THEN GOTO Starved

' ***EATING***
ChooseEating:
PRINT "DO YOU WANT TO EAT (1) POORLY  (2) MODERATELY"
PRINT "OR (3) WELL";
INPUT E
IF E > 3 OR E < 1 THEN GOTO ChooseEating
E = INT(E)
F = F - 8 - 5 * E
IF F < 0 THEN
    F = F + 8 + 5 * E
    PRINT "YOU CAN'T EAT THAT WELL"
    GOTO ChooseEating
END IF
M = M + 200 + (A - 220) / 5 + 10 * RND
L1 = 0
C1 = 0

' ***RIDERS ATTACK***
IF RND * 10 * ((M / 100 - 4) ^ 2 + 72) / ((M / 100 - 4) ^ 2 + 12) > 1 THEN GOTO SelectEvents
PRINT "RIDERS AHEAD.  THEY ";
S5 = 0
IF RND < 0.8 THEN
    PRINT "DON'T ";
    S5 = 1
END IF
PRINT "LOOK HOSTILE"
PRINT "TACTICS"
PRINT "(1) RUN  (2) ATTACK  (3) CONTINUE  (4) CIRCLE WAGONS"
IF RND > 0.2 THEN GOTO GetTactics
S5 = 1 - S5

GetTactics:
INPUT T1
IF T1 < 1 OR T1 > 4 THEN GOTO GetTactics
T1 = INT(T1)

IF S5 = 1 THEN GOTO FriendlyRiders

' Hostile riders
SELECT CASE T1
    CASE 1  ' Run
        M = M + 20
        M1 = M1 - 15
        B = B - 150
        A = A - 40
    CASE 2  ' Attack
        GOSUB ShootingRoutine
        B = B - B1 * 40 - 80
        IF B1 <= 1 THEN
            PRINT "NICE SHOOTING---YOU DROVE THEM OFF"
        ELSEIF B1 > 4 THEN
            PRINT "LOUSY SHOT---YOU GOT KNIFED"
            K8 = 1
            PRINT "YOU HAVE TO SEE OL' DOC BLANCHARD"
        ELSE
            PRINT "KINDA SLOW WITH YOUR COLT .45"
        END IF
    CASE 3  ' Continue
        IF RND > 0.8 THEN
            PRINT "THEY DID NOT ATTACK"
            GOTO SelectEvents
        END IF
        B = B - 150
        M1 = M1 - 15
    CASE 4  ' Circle wagons
        GOSUB ShootingRoutine
        B = B - B1 * 30 - 80
        M = M - 25
        IF B1 <= 1 THEN
            PRINT "NICE SHOOTING---YOU DROVE THEM OFF"
        ELSEIF B1 > 4 THEN
            PRINT "LOUSY SHOT---YOU GOT KNIFED"
            K8 = 1
            PRINT "YOU HAVE TO SEE OL' DOC BLANCHARD"
        ELSE
            PRINT "KINDA SLOW WITH YOUR COLT .45"
        END IF
END SELECT
GOTO CheckRidersResult

FriendlyRiders:
SELECT CASE T1
    CASE 1  ' Run
        M = M + 15
        A = A - 10
    CASE 2  ' Attack
        M = M - 5
        B = B - 100
    CASE 3  ' Continue
        ' Nothing happens
    CASE 4  ' Circle wagons
        M = M - 20
END SELECT

CheckRidersResult:
IF S5 = 1 THEN
    PRINT "RIDERS WERE FRIENDLY, BUT CHECK FOR POSSIBLE LOSSES"
ELSE
    PRINT "RIDERS WERE HOSTILE--CHECK FOR LOSSES"
END IF
IF B < 0 THEN
    PRINT "YOU RAN OUT OF BULLETS AND GOT MASSACRED BY THE RIDERS"
    GOTO GameOver
END IF

' ***SELECTION OF EVENTS***
SelectEvents:
D1 = 0
RESTORE EventData
R1 = 100 * RND

ReadEventData:
D1 = D1 + 1
IF D1 = 16 THEN GOTO HelpfulIndians
READ D
IF R1 > D THEN GOTO ReadEventData

EventData:
DATA 6,11,13,15,17,22,32,35,37,42,44,54,64,69,95

SELECT CASE D1
    CASE 1  ' Wagon breaks down
        PRINT "WAGON BREAKS DOWN--LOSE TIME AND SUPPLIES FIXING IT"
        M = M - 15 - 5 * RND
        M1 = M1 - 8
    CASE 2  ' Ox injures leg
        PRINT "OX INJURES LEG---SLOWS YOU DOWN REST OF TRIP"
        M = M - 25
        A = A - 20
    CASE 3  ' Daughter broke arm
        PRINT "BAD LUCK---YOUR DAUGHTER BROKE HER ARM"
        PRINT "YOU HAD TO STOP AND USE SUPPLIES TO MAKE A SLING"
        M = M - 5 - 4 * RND
        M1 = M1 - 2 - 3 * RND
    CASE 4  ' Ox wanders off
        PRINT "OX WANDERS OFF---SPEND TIME LOOKING FOR IT"
        M = M - 17
    CASE 5  ' Son gets lost
        PRINT "YOUR SON GETS LOST---SPEND HALF THE DAY LOOKING FOR HIM"
        M = M - 10
    CASE 6  ' Unsafe water
        PRINT "UNSAFE WATER--LOSE TIME LOOKING FOR CLEAN SPRING"
        M = M - 10 * RND - 2
    CASE 7  ' Heavy rains / Cold weather
        IF M > 950 THEN
            PRINT "COLD WEATHER---BRRRRRRR!---YOU ";
            IF C > 22 + 4 * RND THEN
                PRINT "HAVE ENOUGH CLOTHING TO KEEP YOU WARM"
            ELSE
                PRINT "DON'T HAVE ENOUGH CLOTHING TO KEEP YOU WARM"
                C1 = 1
                GOTO IllnessRoutine
            END IF
        ELSE
            PRINT "HEAVY RAINS---TIME AND SUPPLIES LOST"
            F = F - 10
            B = B - 500
            M1 = M1 - 15
            M = M - 10 * RND - 5
        END IF
    CASE 8  ' Bandits attack
        PRINT "BANDITS ATTACK"
        GOSUB ShootingRoutine
        B = B - 20 * B1
        IF B < 0 THEN
            PRINT "YOU RAN OUT OF BULLETS---THEY GET LOTS OF CASH"
            T = T / 3
            GOTO BanditInjury
        END IF
        IF B1 <= 1 THEN
            PRINT "QUICKEST DRAW OUTSIDE OF DODGE CITY!!!"
            PRINT "YOU GOT 'EM!"
            GOTO AfterEvents
        END IF
        BanditInjury:
        PRINT "YOU GOT SHOT IN THE LEG AND THEY TOOK ONE OF YOUR OXEN"
        K8 = 1
        PRINT "BETTER HAVE A DOC LOOK AT YOUR WOUND"
        M1 = M1 - 5
        A = A - 20
    CASE 9  ' Fire in wagon
        PRINT "THERE WAS A FIRE IN YOUR WAGON--FOOD AND SUPPLIES DAMAGE"
        F = F - 40
        B = B - 400
        M1 = M1 - RND * 8 - 3
        M = M - 15
    CASE 10  ' Lost in fog
        PRINT "LOSE YOUR WAY IN HEAVY FOG---TIME IS LOST"
        M = M - 10 - 5 * RND
    CASE 11  ' Snake bite
        PRINT "YOU KILLED A POISONOUS SNAKE AFTER IT BIT YOU"
        B = B - 10
        M1 = M1 - 5
        IF M1 < 0 THEN
            PRINT "YOU DIE OF SNAKEBITE SINCE YOU HAVE NO MEDICINE"
            GOTO GameOver
        END IF
    CASE 12  ' Wagon swamped
        PRINT "WAGON GETS SWAMPED FORDING RIVER--LOSE FOOD AND CLOTHES"
        F = F - 30
        C = C - 20
        M = M - 20 - 20 * RND
    CASE 13  ' Wild animals attack
        PRINT "WILD ANIMALS ATTACK!"
        GOSUB ShootingRoutine
        IF B <= 39 THEN
            PRINT "YOU WERE TOO LOW ON BULLETS--"
            PRINT "THE WOLVES OVERPOWERED YOU"
            K8 = 1
            GOTO DiedOfInjuries
        END IF
        IF B1 <= 2 THEN
            PRINT "NICE SHOOTIN' PARTNER---THEY DIDN'T GET MUCH"
        ELSE
            PRINT "SLOW ON THE DRAW---THEY GOT AT YOUR FOOD AND CLOTHES"
        END IF
        B = B - 20 * B1
        C = C - B1 * 4
        F = F - B1 * 8
    CASE 14  ' Hail storm
        PRINT "HAIL STORM---SUPPLIES DAMAGED"
        M = M - 5 - RND * 10
        B = B - 200
        M1 = M1 - 4 - RND * 3
    CASE 15  ' Illness from eating
        IF E = 1 THEN
            GOTO IllnessRoutine
        ELSEIF E = 3 THEN
            IF RND < 0.5 THEN GOTO IllnessRoutine
        ELSE
            IF RND > 0.25 THEN GOTO IllnessRoutine
        END IF
END SELECT
GOTO AfterEvents

HelpfulIndians:
PRINT "HELPFUL INDIANS SHOW YOU WHERE TO FIND MORE FOOD"
F = F + 14

AfterEvents:
' ***MOUNTAINS***
IF M <= 950 THEN GOTO SetDate
IF RND * 10 * ((9 - ((M / 100 - 15) ^ 2 + 72)) / ((M / 100 - 15) ^ 2 + 12)) > 0 THEN GOTO CheckPasses
PRINT "RUGGED MOUNTAINS"
IF RND <= 0.1 THEN
    PRINT "YOU GOT LOST---LOSE VALUABLE TIME TRYING TO FIND TRAIL!"
    M = M - 60
ELSEIF RND <= 0.11 THEN
    PRINT "WAGON DAMAGED!---LOSE TIME AND SUPPLIES"
    M1 = M1 - 5
    B = B - 200
    M = M - 20 - 30 * RND
ELSE
    PRINT "THE GOING GETS SLOW"
    M = M - 45 - RND / 0.02
END IF

CheckPasses:
IF F1 = 1 THEN GOTO CheckBlueMountains
F1 = 1
IF RND < 0.8 THEN GOTO CheckBlizzard
PRINT "YOU MADE IT SAFELY THROUGH SOUTH PASS--NO SNOW"

CheckBlueMountains:
IF M < 1700 THEN GOTO CheckMileage
IF F2 = 1 THEN GOTO CheckMileage
F2 = 1
IF RND < 0.7 THEN GOTO CheckBlizzard

CheckMileage:
IF M > 950 THEN GOTO SetDate
M9 = 1
GOTO SetDate

CheckBlizzard:
PRINT "BLIZZARD IN MOUNTAIN PASS--TIME AND SUPPLIES LOST"
L1 = 1
F = F - 25
M1 = M1 - 10
B = B - 300
M = M - 30 - 40 * RND
IF C < 18 + 2 * RND THEN GOTO IllnessRoutine
GOTO CheckMileage

' ***DYING***
Starved:
PRINT "YOU RAN OUT OF FOOD AND STARVED TO DEATH"
GOTO GameOver

CantAffordDoctor:
T = 0
PRINT "YOU CAN'T AFFORD A DOCTOR"
GOTO DiedOfInjuries

NoMedicine:
PRINT "YOU RAN OUT OF MEDICAL SUPPLIES"

DiedOfInjuries:
PRINT "YOU DIED OF ";
IF K8 = 1 THEN
    PRINT "INJURIES"
ELSE
    PRINT "PNEUMONIA"
END IF

GameOver:
PRINT
PRINT "DUE TO YOUR UNFORTUNATE SITUATION, THERE ARE A FEW"
PRINT "FORMALITIES WE MUST GO THROUGH"
PRINT
PRINT "WOULD YOU LIKE A MINISTER?"
INPUT C$
PRINT "WOULD YOU LIKE A FANCY FUNERAL?"
INPUT C$
PRINT "WOULD YOU LIKE US TO INFORM YOUR NEXT OF KIN?"
INPUT C$
IF C$ = "YES" THEN
    PRINT "THAT WILL BE $4.50 FOR THE TELEGRAPH CHARGE."
    PRINT
ELSE
    PRINT "BUT YOUR AUNT SADIE IN ST. LOUIS IS REALLY WORRIED ABOUT YOU"
    PRINT
END IF
PRINT "WE THANK YOU FOR THIS INFORMATION AND WE ARE SORRY YOU"
PRINT "DIDN'T MAKE IT TO THE GREAT TERRITORY OF OREGON"
PRINT "BETTER LUCK NEXT TIME"
PRINT
PRINT
PRINT TAB(30); "SINCERELY"
PRINT
PRINT TAB(17); "THE OREGON CITY CHAMBER OF COMMERCE"
END

' ***FINAL TURN***
FinalTurn:
F9 = (2040 - M2) / (M - M2)
F = F + (1 - F9) * (8 + 5 * E)
PRINT
PRINT "YOU FINALLY ARRIVED AT OREGON CITY"
PRINT "AFTER 2040 LONG MILES---HOORAY!!!!!"
PRINT "A REAL PIONEER!"
PRINT
F9 = INT(F9 * 14)
D3 = D3 * 14 + F9
F9 = F9 + 1
IF F9 >= 8 THEN F9 = F9 - 7

SELECT CASE F9
    CASE 1: PRINT "MONDAY ";
    CASE 2: PRINT "TUESDAY ";
    CASE 3: PRINT "WEDNESDAY ";
    CASE 4: PRINT "THURSDAY ";
    CASE 5: PRINT "FRIDAY ";
    CASE 6: PRINT "SATURDAY ";
    CASE 7: PRINT "SUNDAY ";
END SELECT

IF D3 <= 124 THEN
    D3 = D3 - 93
    PRINT "JULY "; D3; " 1847"
ELSEIF D3 <= 155 THEN
    D3 = D3 - 124
    PRINT "AUGUST "; D3; " 1847"
ELSEIF D3 <= 185 THEN
    D3 = D3 - 155
    PRINT "SEPTEMBER "; D3; " 1847"
ELSEIF D3 <= 216 THEN
    D3 = D3 - 185
    PRINT "OCTOBER "; D3; " 1847"
ELSEIF D3 <= 246 THEN
    D3 = D3 - 216
    PRINT "NOVEMBER "; D3; " 1847"
ELSE
    D3 = D3 - 246
    PRINT "DECEMBER "; D3; " 1847"
END IF

PRINT
PRINT "FOOD", "BULLETS", "CLOTHING", "MISC. SUPP.", "CASH"
IF B <= 0 THEN B = 0
IF C <= 0 THEN C = 0
IF M1 <= 0 THEN M1 = 0
IF T <= 0 THEN T = 0
IF F <= 0 THEN F = 0
PRINT INT(F), INT(B), INT(C), INT(M1), INT(T)
PRINT
PRINT TAB(11); "PRESIDENT JAMES K. POLK SENDS YOU HIS"
PRINT TAB(17); "HEARTIEST CONGRATULATIONS"
PRINT
PRINT TAB(11); "AND WISHES YOU A PROSPEROUS LIFE AHEAD"
PRINT
PRINT TAB(22); "AT YOUR NEW HOME"
END

' ***SHOOTING SUB-ROUTINE***
ShootingRoutine:
S$(1) = "BANG"
S$(2) = "BLAM"
S$(3) = "POW"
S$(4) = "WHAM"
S6 = INT(RND * 4 + 1)
PRINT "TYPE "; S$(S6)
B3 = TIMER
INPUT C$
B1 = TIMER
B1 = ((B1 - B3) * 3600) - (D9 - 1)
PRINT
IF B1 <= 0 THEN B1 = 0
IF C$ <> S$(S6) THEN B1 = 9
RETURN

' ***FORT PURCHASE SUB-ROUTINE***
GetPurchase:
INPUT P
IF P < 0 THEN
    P = 0
    RETURN
END IF
T = T - P
IF T < 0 THEN
    PRINT "YOU DON'T HAVE THAT MUCH--KEEP YOUR SPENDING DOWN"
    PRINT "YOU MISS YOUR CHANCE TO SPEND ON THAT ITEM"
    T = T + P
    P = 0
END IF
RETURN

' ***ILLNESS SUB-ROUTINE***
IllnessRoutine:
IF 100 * RND < 10 + 35 * (E - 1) THEN
    PRINT "MILD ILLNESS---MEDICINE USED"
    M = M - 5
    M1 = M1 - 2
ELSEIF 100 * RND < 100 - (40 / 4 ^ (E - 1)) THEN
    PRINT "BAD ILLNESS---MEDICINE USED"
    M = M - 5
    M1 = M1 - 5
ELSE
    PRINT "SERIOUS ILLNESS---"
    PRINT "YOU MUST STOP FOR MEDICAL ATTENTION"
    M1 = M1 - 10
    S4 = 1
END IF
IF M1 < 0 THEN GOTO NoMedicine
IF L1 = 1 THEN GOTO CheckMileage
GOTO AfterEvents

' ***IDENTIFICATION OF VARIABLES IN THE PROGRAM***
' A = AMOUNT SPENT ON ANIMALS
' B = AMOUNT SPENT ON AMMUNITION
' B1 = ACTUAL RESPONSE TIME FOR INPUTTING "BANG"
' B3 = CLOCK TIME AT START OF INPUTTING "BANG"
' C = AMOUNT SPENT ON CLOTHING
' C1 = FLAG FOR INSUFFICIENT CLOTHING IN COLD WEATHER
' C$ = YES/NO RESPONSE TO QUESTIONS
' D1 = COUNTER IN GENERATING EVENTS
' D3 = TURN NUMBER FOR SETTING DATE
' D4 = CURRENT DATE
' D9 = CHOICE OF SHOOTING EXPERTISE LEVEL
' E = CHOICE OF EATING
' F = AMOUNT SPENT ON FOOD
' F1 = FLAG FOR CLEARING SOUTH PASS
' F2 = FLAG FOR CLEARING BLUE MOUNTAINS
' F9 = FRACTION OF 2 WEEKS TRAVELED ON FINAL TURN
' K8 = FLAG FOR INJURY
' L1 = FLAG FOR BLIZZARD
' M = TOTAL MILEAGE WHOLE TRIP
' M1 = AMOUNT SPENT ON MISCELLANEOUS SUPPLIES
' M2 = TOTAL MILEAGE UP THROUGH PREVIOUS TURN
' M9 = FLAG FOR CLEARING SOUTH PASS IN SETTING MILEAGE
' P = AMOUNT SPENT ON ITEMS AT FORT
' R1 = RANDOM NUMBER IN CHOOSING EVENTS
' S4 = FLAG FOR ILLNESS
' S5 = "HOSTILITY OF RIDERS" FACTOR
' S6 = SHOOTING WORD SELECTOR
' S$ = VARIATIONS OF SHOOTING WORD
' T = CASH LEFT OVER AFTER INITIAL PURCHASES
' T1 = CHOICE OF TACTICS WHEN ATTACKED
' X = CHOICE OF ACTION FOR EACH TURN
' X1 = FLAG FOR FORT OPTION
